server:
  port: 8500





spring:
  application:
    name: nineWeb
  datasource:
    url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: sixkery
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 30
      minimum-idle: 10
      pool-name: DatebookHikariCP

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8





jwt:
  header: jwtHeader
  secret: eyJleHAiOjE1NDMyMDUyODUsInN1YiI6ImFkbWluIiwiY3JlYXRlZCI6MTU0MDYxMzI4N # 密钥
  expiration: 1000 * 60 * 60 * 12                                               # 过期时间 毫秒
  route:
    login: /auth/login
    refresh: /auth/refresh
    register: /auth/register
basis:
  token:
    # 默认为 true，token 将存入 redis，并具有单点登录功能 设为 false 使用 JWT 交互
    redis: true
    # 是否开启单设备登陆 仅当 token 交互方式为 redis 时生效
    sdl: false
    # token 中存储用户权限数据 设为 true 开启后可避免每次请求再获取用户权限，但有可能导致编辑权限菜单后无法读取到最新权限数据（需用户重新登录）
    storePerms: true
    # token 过期时间 redis 模式有请求自动刷新（分钟）
    tokenExpireTime: 60
    # 用户选择 保存登录状态/记住我 对应 token 过期时间（天）
    saveLoginTime: 7
    # 限制用户登陆错误次数（次）
    loginTimeLimit: 10
    # 错误超过次数后多少分钟后才能继续登录（分钟）
    loginAfterTime: 10

# 忽略 url
ignored:
  # 无需登录认证的请求
  urls:
    - /xboot/oauth2/**
    - /xboot/actuator/**
    - /xboot/admin/**
    - /xboot/dictData/getByType/**
    - /xboot/user/regist
    - /xboot/common/**
    - /druid/**
    - /doc.html
    - /swagger-resources/**
    - /v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /xboot/test/**
  # 限流及黑名单不拦截的路径
  limitUrls:
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico

# 日志输出级别
logging:
  level:
    root: info