server:
  port: 8500

spring:
  application:
    name: nineWeb
  datasource:
    url: jdbc:mysql://localhost:3306/xinguan?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: sixkery
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 30
      minimum-idle: 10
      pool-name: DatebookHikariCP

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: localhost    # Redis服务器地址
    database: 0        # Redis数据库索引（默认为0）
    port: 6379         # Redis服务器连接端口
    password:          # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8    # 连接池中的最大空闲连接
        min-idle: 0    # 连接池中的最小空闲连接
    timeout: 3000ms    # 连接超时时间（毫秒）

mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted     # 全局逻辑删除的实体字段名 (since 3.3.0, 配置后可以忽略不配置步骤 2 )
      logic-delete-value: 1           # 逻辑已删除值 (默认为 1)
      logic-not-delete-value: 0       # 逻辑未删除值 (默认为 0)
  mapper-locations: classpath*:/mapper/*.xml
logging:
  level:
    com.sixkery.basis.api: debug